name: nextset
services:
  nextset-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nextset-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=P@ssw0rd!
      - MSSQL_PID=Developer
    volumes:
      - nextset-db-data:/var/opt/mssql

volumes:
  nextset-db-data: